apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: golang-pipeline
spec:
  params:
  - name: git_url
    default: https://github.com/marco210/Hello9000
    type: string
  - name: imageUrl
    default: marco210/pipedemo
    type: string
  - name: imageTag
    default: last
    type: string
  workspaces:
    - name: kubegen-ws
    - name: docker-reg-creds
  tasks:
  - name: git-clone
    taskRef:
      name: git-clone
    workspaces:
    - name: output
      workspace: kubegen-ws
    params:
    - name: url
      value: $(params.git_url)
  - name: build-go-app
    taskRef:
      name: golang-build
    workspaces:
    - name: source
      workspace: kubegen-ws
    params:
    - name: package
      value: github.com/marco210/Hello9000
    runAfter:
    - git-clone
  - name: dockerfile-lint
    taskRef:
      name: hadolint
    workspaces:
    - name: source
      workspace: kubegen-ws
    runAfter:
    - git-clone
  - name: build-and-push
    taskRef:
      name: kaniko
    workspaces:
    - name: source
      workspace: kubegen-ws
    - name: dockerconfig
      workspace: docker-reg-creds
    params:
    - name: IMAGE
      value: $(params.imageUrl):$(params.imageTag)
    runAfter:
    - dockerfile-lint
